<?php

declare(strict_types=1);

/**
 * This file is part of the AbraFlexiPriceFixer package
 *
 * https://github.com/VitexSoftware/AbraFlexi-pricefixer
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\AbraFlexi\PriceFix;

use AbraFlexi\PriceFix\Bundler;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-11-27 at 18:35:40.
 */
class BundlerTest extends \PHPUnit\Framework\TestCase
{
    protected Bundler $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Bundler();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \AbraFlexi\PriceFix\Bundler::getBundles
     *
     * @todo   Implement testgetBundles().
     */
    public function testgetBundles(): void
    {
        $this->assertEquals('', $this->object->getBundles());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\PriceFix\Bundler::overallPrice
     *
     * @todo   Implement testoverallPrice().
     */
    public function testoverallPrice(): void
    {
        $this->assertEquals('', $this->object->overallPrice());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\PriceFix\Bundler::getSubItemPrice
     *
     * @todo   Implement testgetSubItemPrice().
     */
    public function testgetSubItemPrice(): void
    {
        $this->assertEquals('', $this->object->getSubItemPrice());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\PriceFix\Bundler::saveBundlePrice
     *
     * @todo   Implement testsaveBundlePrice().
     */
    public function testsaveBundlePrice(): void
    {
        $this->assertEquals('', $this->object->saveBundlePrice());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\PriceFix\Bundler::saveProviderPrice
     *
     * @todo   Implement testsaveProviderPrice().
     */
    public function testsaveProviderPrice(): void
    {
        $this->assertEquals('', $this->object->saveProviderPrice());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\PriceFix\Bundler::fixAll
     *
     * @todo   Implement testfixAll().
     */
    public function testfixAll(): void
    {
        $this->assertEquals('', $this->object->fixAll());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
