<?php

namespace Test\AbraFlexi\PriceFix;

use AbraFlexi\PriceFix\SadyAKomplety;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-11-27 at 18:36:36.
 */
class SadyAKompletyTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var SadyAKomplety
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new SadyAKomplety();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }
}
